name: Replicated FOSSA scan
description: Runs FOSSA scans in a standard fashion for Replicated repos
inputs:
  run-tests:
    required: false
    description: Run the test step
    default: 'true'
  api-key:
    required: true
    description: A FOSSA API key
  diff:
    required: false
    description: Only report issues present in main
    default: 'false'
  diff-ref:
    required: false
    description: Ref against which to diff
    default: 'main'
runs:
  using: composite
  steps:
    - name: fossa anaylze
      shell: bash
      env:
        FOSSA_API_KEY: ${{ inputs.api-key }}
      run: fossa analyze
    - name: fossa test
      if: inputs.run-tests == 'true'
      shell: bash
      env:
        FOSSA_API_KEY: ${{ inputs.api-key }}
      run: fossa test ${{ inputs.diff == 'true' && '--diff ' || '' }}${{ inputs.diff == 'true' && inputs.diff-ref || '' }}
