name: Replicated FOSSA scan
description: Runs FOSSA scans in a standard fashion for Replicated repos
inputs:
  run-tests:
    required: false
    description: Run the test step
    default: 'true'
  api-key:
    required: true
    description: A FOSSA API key
  diff:
    required: false
    description: Only report issues present in main
    default: 'false'
  diff-ref:
    required: false
    description: Ref against which to diff
    default: 'main'
  debug:
    required: false
    description: Enable debug logging
    default: 'true'
  experimental-resolver:
    required: false
    description: Enable experimental Go resolver
    default: 'true'
runs:
  using: composite
  steps:
    - name: fossa anaylze
      shell: bash
      env:
        FOSSA_API_KEY: ${{ inputs.api-key }}
      run: fossa analyze ${{ inputs.debug == 'true' && '--debug ' || '' }} ${{ inputs.experimental-resolver == 'true' && '--experimental-use-v3-go-resolver' || '' }}
    - name: fossa test
      if: inputs.run-tests == 'true'
      shell: bash
      env:
        FOSSA_API_KEY: ${{ inputs.api-key }}
      run: fossa test ${{ inputs.debug == 'true' && '--debug ' || '' }}${{ inputs.diff == 'true' && '--diff ' || '' }}${{ inputs.diff == 'true' && inputs.diff-ref || '' }}
    - name: save debug log
      if: always() && inputs.debug == 'true'
      uses: actions/upload-artifact@v3
      with:
        name: fossa-debug-log
        path: "*.debug.json.*"
