name: Install FOSSA CLI
description: Installs the FOSSA CLI and makes it available in \$PATH
inputs:
  version:
    description: Version to install
    default: '3.9.5'
  sha256sum:
    description: The SHA256 checksum for the installer
    default: 4eb3bedd74cc0defad34f605b8fd0ffa1924ae305499b4aa31f9f72588ee919b
runs:
  using: composite
  steps:
    - name: Download archive
      shell: bash
      run: curl -L -o /tmp/fossa.tar.gz https://github.com/fossas/fossa-cli/releases/download/v${{ inputs.version }}/fossa_${{ inputs.version }}_linux_amd64.tar.gz
    - name: Verify checksum
      shell: bash
      run: echo "${{ inputs.sha256sum }} */tmp/fossa.tar.gz" | sha256sum -c -
    - name: Unpack archive
      shell: bash
      run: |
        mkdir -p /opt/fossa/bin
        tar -C /opt/fossa/bin -xvzf /tmp/fossa.tar.gz
    - name: Update PATH
      shell: bash
      run: echo "/opt/fossa/bin" >> ${GITHUB_PATH}
    - name: Clean up download
      shell: bash
      run: rm /tmp/fossa.tar.gz
